Add files via upload
m1Myp/OOP_TSIlinykh_20213 pull request #1
Opened 2021-09-10 15:09 UTC by m1Myp

Task_1_1_1 DONE! (reuse prev year)

2021-09-23 17:09 UTC, molo4evan requested changes

2021-09-29 14:34 UTC, m1Myp commented on Task_1_1_1/src/main/java/HeapSort.java
> +public class HeapSort {
Не совсем понимаю, что от меня хотят т.к. болел

2021-09-29 18:14 UTC, molo4evan commented on Task_1_1_1/src/main/java/HeapSort.java
> +public class HeapSort {
Не понимаешь только по этому треду, или по всем?

Уточню к этому:

Сейчас что классы с кодом, что тестовые классы находятся в корневом пакете.

Нужно перенести их во вложенный пакет с адекватным неймингом, например `ru.nsu.fit.oop.lab1`

Если на лекции не рассказывали про Java-пакеты: https://metanit.com/java/tutorial/3.2.php

2021-09-29 18:21 UTC, molo4evan requested changes

2021-09-29 18:21 UTC, molo4evan commented on Task_1_1_1/src/test/java/HeapSortTests.java
>          int[] arr2 = {99, 23, -38, -93, 0, 0, -67, 8, 39, -34};
2 разных ситуации - 2 разных теста

А вообще - все тест-кейсы довольно однотипны, стоит заменить на `ParametrizedTest` (в гисте есть ссылка на гайд по параметризованным тестам JUnit).

2021-09-29 18:21 UTC, molo4evan commented on Task_1_1_1/src/main/java/HeapSort.java
>          int[] temp = new int[len];
Суть heapsort в том числе - `O(n)` по памяти. Я понимаю, что `2n` - это все еще `O(n)`, но сортировку вполне реально реализовать без выделения дополнительной памяти.

2021-09-30 15:32 UTC, m1Myp commented on Task_1_1_1/src/test/java/HeapSortTests.java
>          int[] arr2 = {99, 23, -38, -93, 0, 0, -67, 8, 39, -34};
Я всегда могу на 2 разных теста перейти, но я решил пошаманить с ParametrizedTest , подключил зависимости а оно работать не очень хочет, можете подсказать в чем проблема?

2021-09-30 15:34 UTC, m1Myp commented on Task_1_1_1/src/test/java/HeapSortTests.java
>          int[] arr2 = {99, 23, -38, -93, 0, 0, -67, 8, 39, -34};
![image](https://user-images.githubusercontent.com/55120919/135486110-70d67019-f921-4e63-a095-5bbf2d461f96.png)
![image](https://user-images.githubusercontent.com/55120919/135486131-25d7e137-2d86-46e8-8d61-11750c5c94fa.png)

2021-09-30 18:41 UTC, m1Myp commented on Task_1_1_1/src/test/java/HeapSortTests.java
>          int[] arr2 = {99, 23, -38, -93, 0, 0, -67, 8, 39, -34};
Проблему нашел, но теперь не запускаются обычные @TEST, гг

2021-09-30 18:43 UTC, m1Myp commented on Task_1_1_1/src/test/java/HeapSortTests.java
>          int[] arr2 = {99, 23, -38, -93, 0, 0, -67, 8, 39, -34};
Решил проблему окончательно

2021-10-01 05:03 UTC, molo4evan commented
Да, и добавь, пожалуйста, в корень settings.gradle. Для сдачи лабы не критично, просто так будет удобнее. Инструкцию я кидал в телегу, она есть в гисте.

2021-10-01 06:11 UTC, molo4evan requested changes

2021-10-01 06:11 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/oop/lab1/HeapSort.java
> +    private static void takeRoot(int[] arr, int len) {
Зачем передавать длину извне?

2021-10-01 06:11 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/oop/lab1/HeapSort.java
> +        /*int t = arr[0];
Этот код нужен на будущее? Почему не удалил?

2021-10-01 06:11 UTC, molo4evan commented on Task_1_1_1/src/test/java/ru/nsu/fit/oop/lab1/HeapSortTest.java
> +    @ValueSource(strings = {"4 5 1 0 -5", "99 23 -38 -93 0 0 -67 8 39 -34"})
Используй `methodSource`. Остальные тесты точно также схлопываются с этим.

2021-10-01 06:39 UTC, m1Myp commented on Task_1_1_1/src/main/java/ru/nsu/fit/oop/lab1/HeapSort.java
> +        arr[0] = returnFirst(arr[last], arr[last] = arr[0]);
Нормальная реализация свапа на Java вещь странная, только если делать свап для элементов массивов, а это очень частный случай, но сделаю

2021-10-01 06:45 UTC, m1Myp commented
> Да, и добавь, пожалуйста, в корень settings.gradle. Для сдачи лабы не критично, просто так будет удобнее. Инструкцию я кидал в телегу, она есть в гисте.

Так вроде же последний файлик...?
![image](https://user-images.githubusercontent.com/55120919/135577163-253ae06b-9cf0-453c-9337-7d5dcc0ca9f7.png)

2021-10-01 07:05 UTC, m1Myp commented on Task_1_1_1/build.gradle
>      testCompile group: 'junit', name: 'junit', version: '4.12'
Потомучто без тест компайла программа не работает, нужна более новая версия градла, как поставлю - исправлю

2021-10-01 07:08 UTC, m1Myp commented on Task_1_1_1/src/main/java/ru/nsu/fit/oop/lab1/HeapSort.java
> +    private static void takeRoot(int[] arr, int len) {
Алгоритмически обосновано тем, что я каждый раз засовываю в конец значения (чтобы потом они в дереве не встречались) и уменьшаю длину, поэтому я передаю буквально урезанное дерево из массива

2021-10-08 05:22 UTC, merged